//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paises2.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public int PlaceId { get; set; }
        public int CategoryId { get; set; }
        public string Comment1 { get; set; }
        public int N_likes { get; set; }
        public int UsarioId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Place Place { get; set; }
    }
}
