//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paises2.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PueblosCiudades
    {
        public decimal CityTownId { get; set; }
        public string CityTownName { get; set; }
        public decimal CountryId { get; set; }
    
        public virtual Paises Paises { get; set; }
    }
}
